/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IconAntDesignAccountBookTwotone: typeof import('~icons/ant-design/account-book-twotone')['default']
    IconAntDesignPicRightOutlined: typeof import('~icons/ant-design/pic-right-outlined')['default']
    IconCusTest: typeof import('~icons/cus/test')['default']
    IconEpApple: typeof import('~icons/ep/apple')['default']
    IconEpChatRound: typeof import('~icons/ep/chat-round')['default']
    IconEphatRound: typeof import('~icons/ep/hat-round')['default']
    IconEtAlarmclock: typeof import('~icons/et/alarmclock')['default']
    'IconIc:baseline4gPlusMobiledata': typeof import('~icons/ic/baseline4g-plus-mobiledata')['default']
    'IconMaterialSymbols:10mp': typeof import('~icons/material-symbols/10mp')['default']
    'IconMaterialSymbols:accountBalanceWallet': typeof import('~icons/material-symbols/account-balance-wallet')['default']
    'IconMaterialSymbols:addShoppingCartSharp': typeof import('~icons/material-symbols/add-shopping-cart-sharp')['default']
    IconMaterialSymbols10mp: typeof import('~icons/material-symbols/10mp')['default']
    IconMaterialSymbols14mp: typeof import('~icons/material-symbols/14mp')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
